def compute_energy_results(data: dict) -> dict:
    """
    Pure Python computation of energy usage and costs from user input + rates.
    This runs before the AI call so Claude gets pre-computed context.
    """
    devices = data.get("devices", [])
    rates = data.get("energy_rates", [])

    rate_lookup = {r["hour"]: r["cost_per_kwh"] for r in rates}
    avg_rate = sum(r["cost_per_kwh"] for r in rates) / len(rates) if rates else 0.12

    breakdown = []
    total_kwh = 0.0

    for device in devices:
        on_watts = device.get("power_on_watts", 0)
        idle_watts = device.get("power_idle_watts", on_watts * 0.05)
        hours_on = device.get("hours_on_per_day", 0)
        hours_idle = device.get("hours_idle_per_day", 0)

        kwh_per_day = (on_watts * hours_on + idle_watts * hours_idle) / 1000
        cost_per_month = kwh_per_day * 30 * avg_rate
        total_kwh += kwh_per_day

        breakdown.append({
            "device_name": device["device_name"],
            "kwh_per_day": round(kwh_per_day, 3),
            "cost_per_month": round(cost_per_month, 2),
        })

    total_cost_per_month = round(total_kwh * 30 * avg_rate, 2)

    sorted_rates = sorted(rates, key=lambda r: r["cost_per_kwh"])
    best_hours = [r["hour"] for r in sorted_rates[:6]]
    worst_hours = [r["hour"] for r in sorted_rates[-3:]]

    cheapest = sorted_rates[0]["cost_per_kwh"] if sorted_rates else avg_rate
    most_expensive = sorted_rates[-1]["cost_per_kwh"] if sorted_rates else avg_rate
    savings_pct = round((1 - cheapest / most_expensive) * 100) if most_expensive else 0
    potential_savings = round(total_cost_per_month * savings_pct / 100, 2)

    phantom_watts = sum(
        device.get("power_on_watts", 0) * 0.05 * device.get("hours_idle_per_day", 0)
        for device in devices
    )
    phantom_kwh = round(phantom_watts / 1000, 3)
    phantom_pct = round(phantom_kwh / total_kwh * 100) if total_kwh else 0

    power_score = _compute_power_score(devices, rates, worst_hours, phantom_pct, savings_pct)

    return {
        "summary": {
            "total_kwh_per_day": round(total_kwh, 3),
            "total_cost_per_month": total_cost_per_month,
        },
        "breakdown": breakdown,
        "optimization": {
            "best_hours": best_hours,
            "worst_hours": worst_hours,
            "potential_savings_percent": savings_pct,
            "potential_monthly_savings_dollars": potential_savings,
        },
        "phantom_load": {
            "total_watts": round(phantom_watts, 1),
            "daily_kwh": phantom_kwh,
            "percentage_of_total": phantom_pct,
        },
        "power_score": power_score,
    }


def _compute_power_score(devices, rates, worst_hours, phantom_pct, savings_pct):
    """
    PowerScore formula: 100 - peak_usage_penalty - inefficiency_penalty + off_peak_bonus
    Always deterministic — never generated by AI.
    """
    # Peak usage penalty: how many hours are devices on during worst (most expensive) hours
    worst_set = set(worst_hours)
    total_on_hours = sum(d.get("hours_on_per_day", 0) for d in devices)
    # Estimate peak usage as proportion of worst hours used (rough heuristic)
    peak_ratio = len(worst_set) / 24
    peak_usage_penalty = round(min(30, peak_ratio * total_on_hours * 5))

    # Inefficiency penalty: phantom load percentage (max 30 points)
    inefficiency_penalty = round(min(30, phantom_pct * 0.6))

    # Off-peak bonus: potential savings % signals how much better they could do (max 20 points)
    off_peak_bonus = round(min(20, savings_pct * 0.2))

    score = 100 - peak_usage_penalty - inefficiency_penalty + off_peak_bonus
    return max(0, min(100, score))
